# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Shark.destroy_all
Shark.create!([
    {name:"Whale Shark (Rhincodon typus)",description:"The whale shark is the largest shark species, and also the biggest fish species in the world. Whale sharks can grow to 65 feet in length and weigh up to 75,000 pounds. Their backs are gray, blue, or brown in color and covered with regularly arranged light spots. Whale sharks are found in warm waters in the Pacific, Atlantic, and Indian Oceans.
    Despite their huge size, whale sharks feed on some of the tiniest creatures in the ocean, including crustaceans and plankton."},

    {name:"Basking Shark (Cetorhinus maximus)",description:"Basking sharks are the second-largest shark (and fish) species. They can grow to up to 40 feet long and weigh up to 7 tons. Like whale sharks, they feed on tiny plankton and may often be seen basking at the ocean surface while they feed by slowly swimming forward and filtering water in through their mouths and out their gills, where the prey is trapped in gill rakers.

    Basking sharks may be found in all the world's oceans, but they are more common in temperate waters. They may also migrate long distances in winter: One shark tagged off Cape Cod was later discovered near Brazil."},
    {name:"Shortfin Mako Shark (Isurus oxyrinchus)",description:"Shortfin mako sharks are thought to be the fastest shark species. These sharks can grow to a length of about 13 feet and a weight of about 1,220 pounds. They have a light underside and a bluish coloration on their back.

    Shortfin mako sharks are found in the pelagic zone (open ocean) in temperate and tropical waters in the Atlantic, Pacific, and Indian oceans and the Mediterranean Sea."},
    {name:"Thresher Sharks (Alopias sp.)",description:"There are three species of thresher sharks: the common thresher (Alopias vulpinus), pelagic thresher (Alopias pelagicus), and the bigeye thresher (Alopias superciliosus). These sharks all have big eyes, small mouths, and long, whip-like upper tail lobes. This whip is used to herd and stun prey. "},
    {name:"Bull Shark (Carcharhinus leucas)",description:"Bull sharks have the dubious distinction of being one of the top three species implicated in unprovoked shark attacks on humans. These large sharks have a blunt snout, a gray back, and light underside, and can grow to a length of about 11.5 feet and weight of about 500 pounds. They tend to frequent warm, shallow, and often murky waters close to shore. "},
    {name:"Tiger Shark (Galeocerdo cuvier)",description:"A tiger shark has a darker stripe on its side, especially in younger sharks. These are large sharks that may grow over 18 feet long and weigh up to 2,000 pounds. Although diving with tiger sharks is an activity some people engage in, tiger sharks are among the sharks most likely to attack humans. "},
    {name:"White Shark (Carcharodon carcharias)",description:"White sharks (more commonly called great white sharks) are among the most feared creatures in the ocean, thanks to the movie Jaws. Their maximum size has been estimated at about 20 feet long and more than 4,000 pounds. Despite its fierce reputation, the great white shark has a curious nature and tends to investigate its prey before eating it. They may release prey they find unpalatable. Some great whites may bite humans but not go on to kill them."},
    {name:"Oceanic Whitetip Shark (Carcharhinus longimanus)",description:"Oceanic whitetip sharks usually live out in the open ocean far from land. They were feared during World War I and II for their potential threat to military personnel on downed planes and sunken ships. These sharks live in tropical and subtropical waters. Their identifying features include their white-tipped first dorsal, pectoral, pelvic, and tail fins, and their long, paddle-like pectoral fins."},
    {name:"Blue Shark (Prionace glauca)",description:"Blue sharks get their name from their coloration: They have dark blue backs, lighter blue sides, and white undersides. The largest recorded blue shark was just over 12 feet long, although they are rumored to grow larger. This is a slender shark with large eyes and a small mouth that lives in temperate and tropical oceans around the world."},
    {name:"Hammerhead Sharks (Sphyrnidae)",description:"There are several species of hammerhead sharks, which are in the family Sphyrnidae. These species include the winghead, mallethead, scalloped hammerhead, scoophead, great hammerhead, and bonnethead sharks. Their oddly-shaped heads give them a wide visual range, which aids their hunting. These sharks inhabit tropical and warm temperate oceans around the world. "},
    {name:"Nurse Shark (Ginglymostoma cirratum)",description:"Nurse sharks are a nocturnal species that prefer to live on the ocean bottom and often seek shelter in caves and crevices. They are found in the Atlantic Ocean from Rhode Island to Brazil and off the coast of Africa. In the Pacific Ocean, they are found from Mexico to Peru."},
    {name:"Blacktip Reef Shark (Carcharhinus melanopterus)",description:"Blacktip reef sharks are easily identified by their black-tipped (bordered by white) fins. These sharks grow to a maximum length of 6 feet​ but are usually between 3 and 4 feet long. They are found in warm, shallow waters over reefs in the Pacific Ocean (including off Hawaii, Australia), in the Indo-Pacific, and ​the Mediterranean Sea. "},
    {name:"Sand Tiger Shark (Carcharias taurus)",description:"The sand tiger shark is also known as the gray nurse shark and ragged-tooth shark. This shark grows to about 14 feet in length. Sand tiger sharks have a flattened snout and long mouth with ragged-looking teeth. Sand tiger sharks have a light brown to greenish back with a light underside. They may have dark spots. They are found in relatively shallow waters (about 6 to 600 feet) in the Atlantic and Pacific Oceans and the Mediterranean Sea."},
    {name:"Lemon Shark (Negaprion brevirostris)",description:"Lemon sharks get their name from their light-colored, brownish-yellow skin. Their color enables them to blend in with their habitat, near the sand at the bottom of the water, which aids their hunting. This is a shark species that is most commonly found in shallow water and can grow to a length of about 11 feet."},
    {name:"Brownbanded Bamboo Shark (Chiloscyllium punctatum)",description:"The brown-banded bamboo shark is a relatively small shark found in shallow waters. Females of this species were discovered to have an amazing ability to store sperm for at least 45 months, giving them the capability to fertilize an egg without ready access to a mate."},
    {name:"Megamouth Shark (Megachasma pelagios)",description:"The megamouth shark species was discovered in 1976 and only about 100 sightings have been confirmed since. This is a relatively large, filter-feeding shark that is thought to live in the Atlantic, Pacific, and Indian Oceans."}
])